# Generated by Django 6.0.1 on 2026-02-26 18:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_medicalcertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Загрузите фотографию товара', max_length=255, null=True, verbose_name='image'),
        ),
    ]
